use_frameworks!

target 'CoreDataSaver_Example' do
  pod 'CoreDataSaver', :path => '../'

  target 'CoreDataSaver_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
